/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package welcomeEmojiDiscordBot

import com.kotlindiscord.kord.extensions.ExtensibleBot
import com.kotlindiscord.kord.extensions.utils.addReaction
import com.kotlindiscord.kord.extensions.utils.env
import dev.kord.common.entity.MessageType
import dev.kord.common.entity.Snowflake
import dev.kord.core.event.message.MessageCreateEvent
import welcomeEmojiDiscordBot.extensions.DebugExtension

val TEST_SERVER_ID = Snowflake(
	env("TEST_SERVER").toLong()  // Get the test server ID from the env vars or a .env file
)

private val TOKEN = env("TOKEN")   // Get the bot' token from the env vars or a .env file

private val EMOJI = env("EMOJI")

suspend fun main() {
	val bot = ExtensibleBot(TOKEN) {
		// Puts "Playing with your feelings" under the bots' username.
		presence {
			playing("with your feelings")
		}

		extensions {
			// Contains the commands of the bot.
			add(::DebugExtension)
		}
	}

	bot.on<MessageCreateEvent> {
		if (message.type == MessageType.UserJoin) {
			message.addReaction(EMOJI)
		}
	}

	bot.start()
}
